
import Colors from "../config/Colors";export const lightTheme = {
  mode: "light",
  primary: Colors.primary,
  secondary: Colors.green10,
  lightPrimary: Colors.lightPrimary,
  heading: Colors.heading,
  lightWhite: Colors.lightWhite,
  lightGrey: Colors.lightGrey,
  grey: Colors.grey,
  white: "white",
  black: "black",
  darkGrey2: Colors.darkGrey2,
  darkGrey: Colors.cartsTitle,
  newInputFieldBorder: Colors.newInputFieldBorder,
  inputFieldBorder: Colors.inputFieldBorder,
  inputFieldBackgroundColor: Colors.inputFieldBackgroundColor,
  inputFieldPlaceholder: Colors.inputFieldPlaceholder,
  detailsText: Colors.desc,
  detailsBorder: Colors.detailsBorder,
  red: "#EF4444",
  cartsBackground: Colors.cartsBackground,
  cartsTitle: Colors.cartsTitle,
  border: "rgba(233, 233, 233, 1)",
  border2: Colors.w1,
  stroke: Colors.stroke,
  chat: Colors.chat,
  desc: Colors.desc,
  skip: Colors.skip,
  primary2: Colors.success2,
  pureWhite: "white",
  pureBlack: "black",
  modal: Colors.modal,
  chat1: Colors.chat1,
  chat2: Colors.chat2,
};

export const darkTheme = {
  mode: "dark",
  primary: Colors.primary,
  secondary: Colors.green10,
  lightPrimary: "#1A1F2B",
  heading: Colors.stroke,
  lightWhite: "#1F2937",
  lightGrey: Colors.heading,
  grey: Colors.lightGrey,
  white: "rgb(0, 0, 0)",
  black: "white",
  darkGrey2: Colors.greyLight,
  darkGrey: Colors.stroke,
  newInputFieldBorder: Colors.cartsTitle,
  inputFieldBorder: Colors.greyLight,
  inputFieldBackgroundColor: "#1E293B",
  inputFieldPlaceholder: Colors.blueLight2,
  detailsText: Colors.blueLight2,
  detailsBorder: "rgb(12, 12, 12)",
  red: "#F87171",
  cartsBackground: "#0F172A",
  cartsTitle: Colors.greyLight4,
  border: "#374151",
  border2: "#111418",
  stroke: Colors.cartsTitle,
  chat: "#C7D2FE",
  desc: Colors.blueLight2,
  skip: Colors.greyLight4,
  primary2: "#8FA9FF",
  pureWhite: "white",
  pureBlack: "black",
  modal: Colors.overlayDark,
  chat1: "rgb(5, 9, 29)",
  chat2: "rgb(0, 0, 2)",
};
